# PATHS
MODEL_PATH = "./src/artifacts/hand_landmarker.task"
CLASSIFIER_PATH_PKL = "./src/artifacts/gesture_classifier_mlp.pkl"
SCALER_PATH = "./src/artifacts/gesture_scaler.pkl"
CLASSIFIER_PATH_ONNX = "./src/artifacts/gesture_classifier_mlp.onnx"
HAS_ONNX = True  # Set to True if you want to use ONNX for inference, False for pickle


# CAMERA
FRAME_WIDTH = 640
FRAME_HEIGHT = 480


# MEDIAPIPE
NUM_HANDS = 1
MIN_HAND_DETECTION_CONFIDENCE = 0.5
MIN_HAND_PRESENCE_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.5


# MOTION GATE
MOTION_BUFFER_SIZE = 8
VELOCITY_THRESHOLD = 0.16
ACCELERATION_THRESHOLD = 0.6


# CLASSIFICATION
STATIC_CONFIDENCE_THRESHOLD = 0.65
DYNAMIC_CONFIDENCE_THRESHOLD = 0.85


# VISUALIZATION
LANDMARK_VISUALIZATION = False
STREAM_VISUALIZATION = True
WINDOW_WIDTH = 320
WINDOW_HEIGHT = 240
INFERENCE_HISTORY_SIZE = 30
